// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt0brh0ESs71eh4dGnUa-4pwiNmIQipGk',
    appId: '1:273442563150:web:f9ca3716a03bf9422acf1f',
    messagingSenderId: '273442563150',
    projectId: 'heyyo-trip-7d7b8',
    authDomain: 'heyyo-trip-7d7b8.firebaseapp.com',
    storageBucket: 'heyyo-trip-7d7b8.firebasestorage.app',
    measurementId: 'G-TL09ZC6G6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0Km0U497KfOlCpejN_UaHV6hu1mkgVNc',
    appId: '1:273442563150:android:7613adecc65447c42acf1f',
    messagingSenderId: '273442563150',
    projectId: 'heyyo-trip-7d7b8',
    storageBucket: 'heyyo-trip-7d7b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLU71EPub2h23q1gvQI7K9Otb6iUUKStM',
    appId: '1:273442563150:ios:4f3068d7caa1cca82acf1f',
    messagingSenderId: '273442563150',
    projectId: 'heyyo-trip-7d7b8',
    storageBucket: 'heyyo-trip-7d7b8.firebasestorage.app',
    iosBundleId: 'com.example.heyyoTrip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLU71EPub2h23q1gvQI7K9Otb6iUUKStM',
    appId: '1:273442563150:ios:4f3068d7caa1cca82acf1f',
    messagingSenderId: '273442563150',
    projectId: 'heyyo-trip-7d7b8',
    storageBucket: 'heyyo-trip-7d7b8.firebasestorage.app',
    iosBundleId: 'com.example.heyyoTrip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt0brh0ESs71eh4dGnUa-4pwiNmIQipGk',
    appId: '1:273442563150:web:7b5094bd0618f0e82acf1f',
    messagingSenderId: '273442563150',
    projectId: 'heyyo-trip-7d7b8',
    authDomain: 'heyyo-trip-7d7b8.firebaseapp.com',
    storageBucket: 'heyyo-trip-7d7b8.firebasestorage.app',
    measurementId: 'G-340FYFHVVQ',
  );
}
